#!/usr/bin/env python3
"""Generates src/adv/markup/ucd.zig: the Unicode properties the text layout needs (Bidi_Class,
Bidi_Mirroring_Glyph, Bidi_Paired_Bracket(_Type), Vertical_Orientation), from the Unicode Character Database
tables that ship with macOS's Perl (lib/unicore/To/*.pl).

    python3 tools/gen_ucd.py [/System/Library/Perl/5.34/unicore] > src/adv/markup/ucd.zig   (from vlc-hddvd/)
"""
import glob
import re
import sys

root = sys.argv[1] if len(sys.argv) > 1 else sorted(glob.glob('/System/Library/Perl/*/unicore'))[-1]


def table(name):
    text = open(f'{root}/To/{name}.pl').read()
    version = re.search(r'Version (\d+\.\d+\.\d+)', text).group(1)
    body = text.split("return <<'END';\n", 1)[1].split('\nEND', 1)[0]
    rows = []
    for line in body.splitlines():
        if not line.strip():
            continue
        lo, hi, v = line.split('\t')
        rows.append((int(lo, 16), int(hi or lo, 16), v))
    return version, rows


def merge(rows):
    out = []
    for lo, hi, v in sorted(rows):
        if out and out[-1][2] == v and out[-1][1] + 1 == lo:
            out[-1] = (out[-1][0], hi, v)
        else:
            out.append((lo, hi, v))
    return out


version, bc = table('Bc')
_, vo = table('Vo')
_, bmg = table('Bmg')
_, bpb = table('Bpb')
_, bpt = table('Bpt')

classes = ['L', 'R', 'AL', 'EN', 'ES', 'ET', 'AN', 'CS', 'NSM', 'BN', 'B', 'S', 'WS', 'ON',
           'LRE', 'LRO', 'RLE', 'RLO', 'PDF', 'LRI', 'RLI', 'FSI', 'PDI']
bc = merge([r for r in bc if r[2] != 'L'])
for r in bc:
    assert r[2] in classes, r
upright = merge([(lo, hi, 'U') for lo, hi, v in vo if v in ('U', 'Tu')])
types = dict(((lo, v) for lo, _, v in bpt))

w = sys.stdout.write
w(f'''//! Unicode Character Database {version} properties for text layout, generated by tools/gen_ucd.py
//! from the UCD's own tables (Unicode license): Bidi_Class (UAX #9), Bidi_Mirroring_Glyph,
//! Bidi_Paired_Bracket and its type, and the code points Vertical_Orientation (UAX #50) sets upright (U, Tu).
//! Do not edit.

pub const BidiClass = enum(u8) {{ {', '.join(c for c in classes)} }};

pub const Range = struct {{ lo: u21, hi: u21 }};
pub const ClassRange = struct {{ lo: u21, hi: u21, c: BidiClass }};
pub const Pair = struct {{ cp: u21, to: u21 }};
pub const Bracket = struct {{ cp: u21, pair: u21, open: bool }};

/// Bidi_Class, every code point not listed is L. Sorted.
pub const bidi_class = [_]ClassRange{{
''')
for lo, hi, v in bc:
    w(f'    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .c = .{v} }},\n')
w('''};

/// Bidi_Mirroring_Glyph. Sorted.
pub const mirror = [_]Pair{
''')
for lo, hi, v in sorted(bmg):
    for cp in range(lo, hi + 1):
        w(f'    .{{ .cp = 0x{cp:X}, .to = 0x{int(v, 16):X} }},\n')
w('''};

/// Bidi_Paired_Bracket and Bidi_Paired_Bracket_Type (open or close). Sorted.
pub const brackets = [_]Bracket{
''')
for lo, hi, v in sorted(bpb):
    assert lo == hi
    w(f'    .{{ .cp = 0x{lo:X}, .pair = 0x{int(v, 16):X}, .open = {"true" if types[lo] == "o" else "false"} }},\n')
w('''};

/// Vertical_Orientation U or Tu: upright in vertical text (everything else is rotated). Sorted.
pub const upright = [_]Range{
''')
for lo, hi, _ in upright:
    w(f'    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X} }},\n')
w('};\n')
